source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in user.gemspec.
gemspec

group :development do
  gem 'pg'
end

gem 'devise', '~> 4.7.1'

gem 'grape'
gem 'jwt'

# To use a debugger
# gem 'byebug', group: [:development, :test]
